import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";
import SecHeader from "@/components/header/SecHeader";
import Footer from "@/components/footer/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "the Online Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // console.log(children);
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="relative">
          <Header />
          <SecHeader />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
